//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace CIB.PhoneBook.Shared.Models
{
    public partial class WhatsAppHookLocation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WhatsAppHookLocation()
        {
            this.WhatsAppHookMessages = new HashSet<WhatsAppHookMessage>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
        public string Thumbnail { get; set; }
        public string ForeignUrl { get; set; }
        public string LocalUrl { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WhatsAppHookMessage> WhatsAppHookMessages { get; set; }
    }
}
